## Numpy array and basics

In [1]:
import numpy as np

## Creating array from lists

In [2]:
array_1d = np.array([1,2,3,4])
print("1D array : ",array_1d)

array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array : ",array_2d)

1D array :  [1 2 3 4]
2D array :  [[1 2 3]
 [4 5 6]]


## List VS Numpy array

In [4]:
py_list = [1,2,3]
print("list multipliccation : ",py_list * 2)

np_array = np.array([1,2,3]) #element wise multiplication
print("array multipliccation : ",np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\nList operation time : ",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\nArray operation time : ",time.time() - start)


list multipliccation :  [1, 2, 3, 1, 2, 3]
array multipliccation :  [2 4 6]

List operation time :  0.12018561363220215

Array operation time :  0.016312599182128906


## Creating array from scratch

In [14]:
zeros = np.zeros((3,4)) # 3 rows 4 columns
print("zeros array : \n",zeros)

ones = np.ones((4,3)) # 4 rows 3 columns
print("ones array : \n",ones)

# array of constant element
full = np.full((2,2),4)
print("full array : \n",full)

# random element array/matrices
random = np.random.random((4,5))
print("random array : \n",random) # random values will fluctuate between 0s and 1s 

# sequence array
sequence = np.arange(0,11,2) # (start , stop(exclusive) , step)
print("sequence array : \n",sequence)


zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[4 4]
 [4 4]]
random array : 
 [[0.66018794 0.17775785 0.17209974 0.76481654 0.97695953]
 [0.82343314 0.34553185 0.75869139 0.48217831 0.52973413]
 [0.59768436 0.69169179 0.79472026 0.07386175 0.63042158]
 [0.90407247 0.52085904 0.09050183 0.41971731 0.80960781]]
sequence array : 
 [ 0  2  4  6  8 10]


## Vector, Matrix and Tensor

In [15]:
vector = np.array([1,2,3])
print("vector :\n",vector)

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("matrix :\n",matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("tensor :\n",tensor)


vector :
 [1 2 3]
matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor :
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [21]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])


arr2 = np.array([[1,2,3], 
                [4,5,6],
                [7,8,"9"]])


arr3 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9.9]])


# arr = np.array([[1,2,3], ## will not throw error but prefer similar type of element in numpy array
#                 [4,5,6],
#                 [7,8,True]])


print("Shape : ",arr1.shape) # m x n (rows x columns)

print("Dimensions : ",arr1.ndim) # 1d / 2d / 3d ...

print("Size : ",arr1.size) # number of elements in a matrix

print("Datatype of array 1 : ",arr1.dtype) 
print("Datatype of array 2 : ",arr2.dtype) 
print("Datatype of array 3: ",arr3.dtype) 


Shape :  (3, 3)
Dimensions :  2
Size :  9
Datatype of array 1 :  int64
Datatype of array 2 :  <U21
Datatype of array 3:  float64


## Array reshaping

In [ ]:
arr = np.arange(12)
print("Original array :", arr)

reshaped = arr.reshape((3,4))
print("reshaped array : \n",reshaped)

flattened = reshaped.flatten()
print("flattened array : \n",flattened)

# ravel returns view instead of copy
raveled = reshaped.ravel()
print("raveled array : \n",raveled)

# Transpose (mxn -> nxm)
transpose = reshaped.T
print("transposed array : \n",transpose)


Original array : [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
