## Numpy array operation

In [10]:
import numpy as np

In [11]:
arr = np.array(range(11))
print(arr)
print("Basic Slicing : ",arr[2:7])
print("Step Slicing : ",arr[::2])
print("Negative Slicing : ",arr[-2])
print("Negative Slicing : ",arr[::-2])

[ 0  1  2  3  4  5  6  7  8  9 10]
Basic Slicing :  [2 3 4 5 6]
Step Slicing :  [ 0  2  4  6  8 10]
Negative Slicing :  9
Negative Slicing :  [10  8  6  4  2  0]


In [18]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element : ",arr_2d[2,1])
print("Entire Row : ",arr_2d[2])
print("Entire Column : ",arr_2d[:,2])

Specific Element :  8
Entire Row :  [7 8 9]
Entire Column :  [3 6 9]


## Sorting

In [32]:
unsorted = np.array([2,3,1,5,2,8,4,3])
print("Sorted Array : ",np.sort(unsorted))

unsorted_2d = np.array([[1,2],[9,8],[5,6]])
print("Sorted 2d array with columns : \n",np.sort(unsorted_2d,axis=0))
print("Sorted 2d array with rows : \n",np.sort(unsorted_2d,axis=1))

Sorted Array :  [1 2 2 3 3 4 5 8]
Sorted 2d array with columns : 
 [[1 2]
 [5 6]
 [9 8]]
Sorted 2d array with rows : 
 [[1 2]
 [8 9]
 [5 6]]


## Filtering

In [12]:
numbers = np.array(range(11))
even_numbers = numbers[numbers % 2 == 0]
odd_numbers = numbers[numbers % 2 != 0]
print("Even Numbers : ",even_numbers)
print("Odd Numbers : ",odd_numbers)

Even Numbers :  [ 0  2  4  6  8 10]
Odd Numbers :  [1 3 5 7 9]


## Filter with Mask

In [13]:
mask = numbers > 5
print("Numbers greater than 5 are ",numbers[mask])

Numbers greater than 5 are  [ 6  7  8  9 10]


## Fancy Indexing and np.where

In [32]:
nums = np.array([23,3,4,54,43])
indices = [1,2,3]
print("indices : ",nums[indices])

where = numbers > 5
print("where result : ",numbers[where])

indices :  [ 3  4 54]
where result :  [ 6  7  8  9 10]


## condition with where array

In [35]:
condition_1 = np.where(numbers > 5, numbers * 4, numbers)
condition_2 = np.where(numbers > 5, numbers , numbers)
condition_3 = np.where(numbers > 5, True, False)
print("condition 1 with where array : ",condition_1)
print("condition 2 with where array : ",condition_2)
print("condition 3 with where array : ",condition_3)

condition 1 with where array :  [ 0  1  2  3  4  5 24 28 32 36 40]
condition 2 with where array :  [ 0  1  2  3  4  5  6  7  8  9 10]
condition 3 with where array :  [False False False False False False  True  True  True  True  True]


## Concatenate

In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("array concatenate : ",np.concatenate((arr1,arr2)))

array concatenate :  [1 2 3 4 5 6]


## compatibility


In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("shape compatibility 1: ",a.shape == b.shape)
print("shape compatibility 2: ",a.shape == b.shape != c.shape)

shape compatibility 1:  True
shape compatibility 2:  True


## Addition of rows and columns

In [50]:
original = np.array([[1,2],
                     [3,4]])
new_row = np.array([5,6])
new_colm = np.array([[8],
                    [9]])
result_row = np.vstack((original,new_row)) #vstack will add new row
result_colm = np.hstack((original,new_colm)) #hstack will add new column
print("Original array : \n",original)
print("New array with new row : \n",result_row)
print("New array with new column : \n",result_colm)

Original array : 
 [[1 2]
 [3 4]]
New array with new row : 
 [[1 2]
 [3 4]
 [5 6]]
New array with new column : 
 [[1 2 8]
 [3 4 9]]


## Deleting

In [67]:
ar = np.array([1,2,3,4,5])
ar_2d = np.array([[1,2,3],
                  [4,5,6]])
print("1d array after deletion : ",np.delete(ar,3))
print("2d array after deletion of row: ",np.delete(ar_2d,1,axis = 0))
print("2d array after deletion of column: \n",np.delete(ar_2d,1,axis = 1))


1d array after deletion :  [1 2 3 5]
2d array after deletion of row:  [[1 2 3]]
2d array after deletion of column: 
 [[1 3]
 [4 6]]
